image: xxx/docker/node:10.12.0-alpine

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_NAME}
  paths:
   - node_modules/

job-build:
  stage: build
  only:
    - master
    - feature/init
  tags:
    - shell
  script:
    - npm set registry https://registry.npm.taobao.org
    - npm install --progress=false
    - npm run build
  artifacts:  
    expire_in: 1 week
    paths:
      - dist

job-release:
  stage: deploy
  only:
    - master
  tags:
    - shell
  script:
    - docker build -t xxx/dashboard/dashboard:${CI_COMMIT_SHA:0:8} .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker-registry.xxx 
    - docker push xxx/dashboard/dashboard:${CI_COMMIT_SHA:0:8}
  when: manual